stages:
  - notify

notify_discord:
  stage: notify
  only:
    - main
  script:
    - |
      COMMIT_SHA=$(echo "$CI_COMMIT_SHORT_SHA")
      COMMIT_MESSAGE=$(git log -1 --pretty=%B)
      ACTOR=$(echo "$GITLAB_USER_NAME")
      curl -X POST -H "Content-Type: application/json" \
      -d '{
            "content": "<@&1237702910582980699>",
            "embeds": [{
              "title": "FRONT - New commit merged to main branch!",
              "description": "A new commit has been merged to the main branch. Here are the details:",
              "color": 10181046,
              "fields": [
                {
                  "name": "Commit Message",
                  "value": "'"${COMMIT_MESSAGE}"'",
                  "inline": false
                },
                {
                  "name": "Commit SHA",
                  "value": "'"${COMMIT_SHA}"'",
                  "inline": true
                },
                {
                  "name": "Author",
                  "value": "'"${ACTOR}"'",
                  "inline": true
                }
              ],
              "footer": {
                "text": "GitLab CI",
                "icon_url": "https://about.gitlab.com/images/press/logo/png/gitlab-icon-rgb.png"
              },
              "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
            }]
          }' \
      $DISCORD_WEBHOOK_URL
  environment:
    name: production
