stages:
  - test
include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

gemnasium_dependency_scanning:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_IID

code_quality:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

Static Code Analysis:
  image: node:latest
  stage: test
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run lint
