# stages:
#   - test
# include:
#   - template: Jobs/Code-Quality.gitlab-ci.yml
#   - template: Jobs/Dependency-Scanning.gitlab-ci.yml

# gemnasium-dependency_scanning:
#   stage: test
#   only:
#     - develop
#     - master
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#     - if: $CI_MERGE_REQUEST_IID

# code_quality:
#   stage: test
#   only:
#     - develop
#     - master
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# Static Code Analysis:
#   image: node:latest
#   stage: test
#   only:
#     - develop
#     - master
#   script:
#     - npm install -g pnpm
#     - pnpm install
#     - pnpm run lint

##############################################################################
## Sans rancune, je ne suis pas un rageux mais go faire ma CI en mode chill ##
##############################################################################

stages:
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Build docker image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  only:
    - messages
    - messagegrp/feat/helm-argo
  script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

Build staging helm chart:
  stage: build
  only:
    - messages
    - messagegrp/feat/helm-argo
  image: dtzar/helm-kubectl
  script:
    - helm lint helm/beepenmoinsbien
    - helm package helm/beepenmoinsbien --app-version $CI_COMMIT_TAG
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@beepenmoinsbien-0.1.0.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/staging/charts"

Build stable helm chart:
  stage: build
  only:
    - messages
    - messagegrp/feat/helm-argo
  image: dtzar/helm-kubectl
  when: manual
  script:
    - helm lint helm/beepenmoinsbien
    - helm package helm/beepenmoinsbien --app-version $CI_COMMIT_TAG
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@beepenmoinsbien-0.1.0.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"