replicaCount: 1

imagePullSecrets:
  - name: beep-registry

image:
  repository: 'milou666/beep-front'
  pullPolicy: Always
  port: 8080
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: 'if you see this, it means that the ingress is not working properly'
      paths:
        - /

resources: {}

backend:
  url: 'if you see this, it means that the backend url is not working properly'
